import { describe,it,expect,vi,afterEach } from 'vitest';
import { hostProfileImages,uploadSignatureImage } from './imageHosting';
import { defaultProfile } from '../data/defaultProfile';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
function configure(){vi.stubEnv('VITE_CLOUDINARY_CLOUD_NAME','signature-test');vi.stubEnv('VITE_CLOUDINARY_UPLOAD_PRESET','signature_images');}
describe('hosted image preparation',()=>{
 it('explains missing hosting without making a network request',async()=>{vi.stubEnv('VITE_CLOUDINARY_CLOUD_NAME','');const request=vi.fn();vi.stubGlobal('fetch',request);await expect(uploadSignatureImage('data:image/png;base64,YQ==')).rejects.toThrow('not connected');expect(request).not.toHaveBeenCalled();});
 it('uploads optimized files and replaces only local image fields',async()=>{configure();const request=vi.fn().mockResolvedValue({ok:true,json:async()=>({secure_url:'https://res.cloudinary.com/signature-test/image/upload/v1/test.jpg'})});vi.stubGlobal('fetch',request);const profile={...defaultProfile,mode:'business',photoUrl:'data:image/jpeg;base64,Yg==',logoUrl:'https://example.com/logo.png'};const result=await hostProfileImages(profile);expect(result.photoUrl).toContain('https://res.cloudinary.com/');expect(result.logoUrl).toBe(profile.logoUrl);expect(profile.photoUrl).toContain('data:');expect(request.mock.calls[0][1].body.get('file').type).toBe('image/jpeg');expect(request.mock.calls[0][1].body.get('upload_preset')).toBe('signature_images');await hostProfileImages(profile);expect(request).toHaveBeenCalledTimes(1);});
 it('rejects an upload API error without returning a fake image URL',async()=>{configure();vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:400}));await expect(uploadSignatureImage('data:image/png;base64,Yw==')).rejects.toThrow('rejected');});
 it('rejects oversized files and non-raster formats',async()=>{configure();await expect(uploadSignatureImage('data:image/png;base64,'+'A'.repeat(200000))).rejects.toThrow('resizing');await expect(uploadSignatureImage('data:image/svg+xml;base64,YQ==')).rejects.toThrow('JPG or PNG');});
 it('rejects unexpected provider URLs',async()=>{configure();vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({secure_url:'https://unrelated.example/photo.png'})}));await expect(uploadSignatureImage('data:image/png;base64,ZA==')).rejects.toThrow('unexpected');});
});
